### PR TITLE
test: a test to capture cause of production errors

### LINKED ISSUE #3266: Malicious requests cause 500 errors
`owner:rcross@amsl.com` `type_defect`   |    by rcross@amsl.com

___

Validate URL parameters to prevent 500 errors

Examples:
https://mailarchive.ietf.org/arch/browse/email_list%20=%20'12345%5C'%22%5C%5C%5C'%5C%5C%22);%7C%5D*%5Cx00%7B%5Cr%5Cn%3C%5Cx00%3E%EF%BF%BD%5C'%5C'%F0%9F%92%A1'/

https://mailarchive.ietf.org/arch/search/?f_from=%5C&not-0-field=text%C2%AC-0-qualifier=contains%C2%AC-0-value=1&q=1&qdr=d&query-0-field=text&query-0-qualifier=contains&query-0-value=1&so=date&sso=frm

https://mailarchive.ietf.org/arch/search/f_from=%5C&qdr=d&token=5PqpKyzW1ZNoPWbM

___
_Issue migrated from trac:3266 at 2022-03-03 15:02:53 +0000_

### PR DESCRIPTION
**Pull request by rpcross**
The error in production caused by bogus request

OperationalError at /arch/browse/email_list = '12345\'"\\\'\\");|]*\x00{\r\n<\x00>�\'\'💡'/
(1267, "Illegal mix of collations (utf8mb3_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='")

### CODE REVIEW

**Comment by rjsparks** [comment]
Is there a commit missing here? All I see so far are changes to a test.

**Comment by rpcross** [comment]
This PR is primarily is to preserve the knowledge learned about this particular error in production. The fix is to migrate database tables from utf8mb3 to utf8mb4 (no code changes). Since the error is quite rare I want to consider spending the time doing the migration to Postgres instead.

**Comment by rjsparks** [comment]
So merging the commit doesn't fix/close #3266 then, and the name of the PR should change to reflect that this is just capturing knowledge. Please adjust the title and description.

**Review by Xcalibur53 — COMMENTED** [review]
backend/mlarchive/tests/archive/views.py

**Pull request merged**
